// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Slug                 string   `protobuf:"bytes,6,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Blog) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type ListBlogsRequest struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	SortBy               string   `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogsRequest) Reset()         { *m = ListBlogsRequest{} }
func (m *ListBlogsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBlogsRequest) ProtoMessage()    {}
func (*ListBlogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{1}
}

func (m *ListBlogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogsRequest.Unmarshal(m, b)
}
func (m *ListBlogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogsRequest.Marshal(b, m, deterministic)
}
func (m *ListBlogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogsRequest.Merge(m, src)
}
func (m *ListBlogsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBlogsRequest.Size(m)
}
func (m *ListBlogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogsRequest proto.InternalMessageInfo

func (m *ListBlogsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListBlogsRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *ListBlogsRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type ListBlogsResponse struct {
	Blogs                []*Blog  `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	NextPage             int32    `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogsResponse) Reset()         { *m = ListBlogsResponse{} }
func (m *ListBlogsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlogsResponse) ProtoMessage()    {}
func (*ListBlogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{2}
}

func (m *ListBlogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogsResponse.Unmarshal(m, b)
}
func (m *ListBlogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogsResponse.Marshal(b, m, deterministic)
}
func (m *ListBlogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogsResponse.Merge(m, src)
}
func (m *ListBlogsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBlogsResponse.Size(m)
}
func (m *ListBlogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogsResponse proto.InternalMessageInfo

func (m *ListBlogsResponse) GetBlogs() []*Blog {
	if m != nil {
		return m.Blogs
	}
	return nil
}

func (m *ListBlogsResponse) GetNextPage() int32 {
	if m != nil {
		return m.NextPage
	}
	return 0
}

type GetBlogRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlogRequest) Reset()         { *m = GetBlogRequest{} }
func (m *GetBlogRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlogRequest) ProtoMessage()    {}
func (*GetBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{3}
}

func (m *GetBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlogRequest.Unmarshal(m, b)
}
func (m *GetBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlogRequest.Marshal(b, m, deterministic)
}
func (m *GetBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlogRequest.Merge(m, src)
}
func (m *GetBlogRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlogRequest.Size(m)
}
func (m *GetBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlogRequest proto.InternalMessageInfo

func (m *GetBlogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateBlogRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBlogRequest) Reset()         { *m = CreateBlogRequest{} }
func (m *CreateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBlogRequest) ProtoMessage()    {}
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{4}
}

func (m *CreateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBlogRequest.Unmarshal(m, b)
}
func (m *CreateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBlogRequest.Marshal(b, m, deterministic)
}
func (m *CreateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBlogRequest.Merge(m, src)
}
func (m *CreateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBlogRequest.Size(m)
}
func (m *CreateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBlogRequest proto.InternalMessageInfo

func (m *CreateBlogRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBlogRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateBlogRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateBlogRequest struct {
	Blog                 *Blog    `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	UpdateMask           []string `protobuf:"bytes,2,rep,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBlogRequest) Reset()         { *m = UpdateBlogRequest{} }
func (m *UpdateBlogRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBlogRequest) ProtoMessage()    {}
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{5}
}

func (m *UpdateBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBlogRequest.Unmarshal(m, b)
}
func (m *UpdateBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBlogRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBlogRequest.Merge(m, src)
}
func (m *UpdateBlogRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBlogRequest.Size(m)
}
func (m *UpdateBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBlogRequest proto.InternalMessageInfo

func (m *UpdateBlogRequest) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func (m *UpdateBlogRequest) GetUpdateMask() []string {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteBlogRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBlogRequest) Reset()         { *m = DeleteBlogRequest{} }
func (m *DeleteBlogRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBlogRequest) ProtoMessage()    {}
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{6}
}

func (m *DeleteBlogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBlogRequest.Unmarshal(m, b)
}
func (m *DeleteBlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBlogRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBlogRequest.Merge(m, src)
}
func (m *DeleteBlogRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBlogRequest.Size(m)
}
func (m *DeleteBlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBlogRequest proto.InternalMessageInfo

func (m *DeleteBlogRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Blog)(nil), "proto.Blog")
	proto.RegisterType((*ListBlogsRequest)(nil), "proto.ListBlogsRequest")
	proto.RegisterType((*ListBlogsResponse)(nil), "proto.ListBlogsResponse")
	proto.RegisterType((*GetBlogRequest)(nil), "proto.GetBlogRequest")
	proto.RegisterType((*CreateBlogRequest)(nil), "proto.CreateBlogRequest")
	proto.RegisterType((*UpdateBlogRequest)(nil), "proto.UpdateBlogRequest")
	proto.RegisterType((*DeleteBlogRequest)(nil), "proto.DeleteBlogRequest")
}

func init() { proto.RegisterFile("proto/blog.proto", fileDescriptor_fc5203cdc85000bc) }

var fileDescriptor_fc5203cdc85000bc = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xc9, 0x67, 0x9b, 0x09, 0x94, 0x66, 0x11, 0x5c, 0xf1, 0xd0, 0x18, 0x2f, 0x39, 0x55,
	0xd0, 0x37, 0xa8, 0x82, 0x08, 0x0a, 0x12, 0xe9, 0xc5, 0x4b, 0x48, 0xcd, 0x10, 0x42, 0xd3, 0x6c,
	0xdc, 0xdd, 0x80, 0x7d, 0x0a, 0x5f, 0x59, 0x76, 0x42, 0x25, 0xc6, 0xd3, 0xce, 0xfc, 0xe7, 0x63,
	0xff, 0xf3, 0x83, 0x65, 0x27, 0x85, 0x16, 0x37, 0xbb, 0x46, 0x54, 0x6b, 0x0a, 0x99, 0x47, 0x4f,
	0xf2, 0x6d, 0x81, 0xbb, 0x69, 0x44, 0xc5, 0x16, 0x60, 0xd7, 0x25, 0xb7, 0x62, 0x2b, 0x75, 0x32,
	0xbb, 0x2e, 0xd9, 0x39, 0xcc, 0x7a, 0x85, 0x32, 0xaf, 0x4b, 0x6e, 0x93, 0xe8, 0x9b, 0xf4, 0xa9,
	0x64, 0x67, 0xe0, 0xe9, 0x5a, 0x37, 0xc8, 0x9d, 0xd8, 0x4a, 0x83, 0x6c, 0x48, 0x18, 0x03, 0xb7,
	0x2d, 0x0e, 0xc8, 0x5d, 0x12, 0x29, 0x66, 0x31, 0x84, 0x25, 0xaa, 0x0f, 0x59, 0x77, 0xba, 0x16,
	0x2d, 0xf7, 0xa8, 0x34, 0x96, 0xcc, 0x94, 0x6a, 0xfa, 0x8a, 0xfb, 0xc3, 0x94, 0x89, 0x93, 0x77,
	0x58, 0x3e, 0xd7, 0x4a, 0x1b, 0x53, 0x2a, 0xc3, 0xcf, 0x1e, 0x95, 0x36, 0x7d, 0x5d, 0x51, 0x21,
	0xd9, 0xf3, 0x32, 0x8a, 0x8d, 0x41, 0x25, 0xa4, 0xce, 0x77, 0x47, 0x32, 0x18, 0x64, 0xbe, 0x49,
	0x37, 0x47, 0x76, 0x01, 0x73, 0x21, 0x4b, 0x94, 0xa6, 0x32, 0x78, 0x9c, 0x51, 0xbe, 0x39, 0x26,
	0x6f, 0x10, 0x8d, 0x76, 0xab, 0x4e, 0xb4, 0x0a, 0xd9, 0x15, 0x78, 0x86, 0x8b, 0xe2, 0x56, 0xec,
	0xa4, 0xe1, 0x6d, 0x38, 0x00, 0x5a, 0x9b, 0xa6, 0x6c, 0xa8, 0xb0, 0x4b, 0x08, 0x5a, 0xfc, 0xd2,
	0x39, 0x99, 0xb0, 0xc9, 0xc4, 0xdc, 0x08, 0xaf, 0x45, 0x85, 0x49, 0x0c, 0x8b, 0x47, 0xa4, 0x9d,
	0x27, 0xbb, 0x13, 0x96, 0x49, 0x0e, 0xd1, 0xbd, 0xc4, 0x42, 0xe3, 0xb8, 0xe9, 0x44, 0xcc, 0x1a,
	0x11, 0xfb, 0x65, 0x6b, 0x8f, 0xd9, 0x4e, 0x38, 0x3a, 0xff, 0x38, 0x26, 0x5b, 0x88, 0xb6, 0x5d,
	0x39, 0xf9, 0x60, 0x05, 0xae, 0x71, 0x4f, 0x1f, 0x4c, 0xce, 0xa2, 0x02, 0x5b, 0x41, 0xd8, 0xd3,
	0x54, 0x7e, 0x28, 0xd4, 0x9e, 0xdb, 0xb1, 0x93, 0x06, 0x19, 0x0c, 0xd2, 0x4b, 0xa1, 0xf6, 0xc9,
	0x35, 0x44, 0x0f, 0xd8, 0xe0, 0xdf, 0xb5, 0x93, 0xe3, 0x76, 0x3e, 0xed, 0xbd, 0xfb, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xe4, 0x9d, 0x58, 0xb7, 0x63, 0x02, 0x00, 0x00,
}
